# ~/.config/starship.toml
add_newline = true
format = """$username$hostname$directory$git_branch$git_status$cmd_duration
$character"""

[character]
success_symbol = "[›](bold green)"
error_symbol = "[›](bold red)"

[directory]
truncation_length = 3
truncation_symbol = "…/"
